# Generated by Django 3.1.4 on 2020-12-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='movie',
            name='Rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
